listen_addresses = '*'
shared_preload_libraries = 'timescaledb'

max_connections = 200

max_wal_size = 2GB

timescaledb.max_background_workers = 100

max_worker_processes = 116

max_parallel_workers = 16

log_min_error_statement = PANIC
