{
 "title": "Ускорение",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Ускорение",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"accel_x\" FROM raw WHERE (entity = 'accelerometer' AND attr = 'accel_x' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"accel_y\" FROM raw WHERE (entity = 'accelerometer' AND attr = 'accel_y' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"accel_z\" FROM raw WHERE (entity = 'accelerometer' AND attr = 'accel_z' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    }
   ]
  },
  {
   "title": "Ускорение",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "rawSql": "SELECT value AS \"accel_x\", \"time\" FROM math WHERE ($__timeFilter(\"time\") AND entity = 'accelerometer' AND attr = 'accel_x') ORDER BY \"time\" ASC "
    },
    {
     "rawSql": "SELECT value AS \"accel_y\", \"time\" FROM math WHERE ($__timeFilter(\"time\") AND entity = 'accelerometer' AND attr = 'accel_y') ORDER BY \"time\" ASC "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"accel_z\" FROM math WHERE (entity = 'accelerometer' AND attr = 'accel_z' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    }
   ]
  },
  {
   "title": "Угловая скорость",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"gyro_x\" FROM raw WHERE (entity = 'accelerometer' AND attr = 'gyro_x' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"gyro_y\" FROM raw WHERE (entity = 'accelerometer' AND attr = 'gyro_y' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    },
    {
     "rawSql": "SELECT \"time\", value AS \"gyro_z\" FROM raw WHERE (entity = 'accelerometer' AND attr = 'gyro_z' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    }
   ]
  },
  {
   "title": "Температура",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", value AS \"temp\" FROM raw WHERE (entity = 'accelerometer' AND attr = 'temperature' AND $__timeFilter(\"time\")) ORDER BY \"time\" ASC "
    }
   ]
  }
 ]
}